{{- if .Values.crds.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api.crdInstall" . }}-core
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
data:
{{- range $path, $_ := .Files.Glob "files/core/**.json" }}
  {{ printf "%s/%s" (trimPrefix "files/core" (dir $path)) (base $path) | trimPrefix "/" | replace "/" "__" }}: |
{{ $.Files.Get $path | indent 4 -}}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api.crdInstall" . }}-controlplane
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
data:
{{- range $path, $_ := .Files.Glob "files/controlplane/**.json" }}
  {{ printf "%s/%s" (trimPrefix "files/controlplane" (dir $path)) (base $path) | trimPrefix "/" | replace "/" "__" }}: |
{{ $.Files.Get $path | indent 4 -}}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api.crdInstall" . }}-bootstrap
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
data:
{{- range $path, $_ := .Files.Glob "files/bootstrap/**.json" }}
  {{ printf "%s/%s" (trimPrefix "files/bootstrap" (dir $path)) (base $path) | trimPrefix "/" | replace "/" "__" }}: |
{{ $.Files.Get $path | indent 4 -}}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api.crdInstall" . }}-kustomization
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
data:
  kustomization.json: |
{{ $.Files.Get "files/kustomization.json" | indent 4 }}
---
{{- end }}
