{{- if .Values.crds.install }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "cluster-api.crdInstall" . }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-6"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'RunAsAny'
  volumes:
  - 'configMap'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
{{- end }}
