{{- if .Values.crds.install }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cluster-api.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-1"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
        {{- include "cluster-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cluster-api.crdInstall" . }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kubectl
        image: "{{ .Values.images.domain }}/giantswarm/docker-kubectl:latest"
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset

          cd /files
          tar xzf core.tar.gz
          tar xzf bootstrap.tar.gz
          tar xzf controlplane.tar.gz

          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.

          kubectl apply -k /files 2>&1

          # After updating CRDs the cluster-operator will sometimes stop reconciling CRDs,
          # so here we mitigate that issue by restarting it.
          for deployment in $(kubectl get deployment -l app.kubernetes.io/name=cluster-operator -o name); do
            kubectl rollout restart -n giantswarm "$deployment"
          done
        volumeMounts:
        - name: {{ include "cluster-api.crdInstall" . }}-core
          mountPath: /files/core.tar.gz
          subPath: core.tar.gz
          readOnly: true
        - name: {{ include "cluster-api.crdInstall" . }}-controlplane
          mountPath: /files/controlplane.tar.gz
          subPath: controlplane.tar.gz
          readOnly: true
        - name: {{ include "cluster-api.crdInstall" . }}-bootstrap
          mountPath: /files/bootstrap.tar.gz
          subPath: bootstrap.tar.gz
          readOnly: true
        - name: {{ include "cluster-api.crdInstall" . }}-kustomization
          mountPath: /files/kustomization.yaml
          subPath: kustomization.yaml
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: {{ include "cluster-api.crdInstall" . }}-core
        configMap:
          name: {{ include "cluster-api.crdInstall" . }}-core
          items:
          - key: core.tar.gz
            path: core.tar.gz
      - name: {{ include "cluster-api.crdInstall" . }}-controlplane
        configMap:
          name: {{ include "cluster-api.crdInstall" . }}-controlplane
          items:
          - key: controlplane.tar.gz
            path: controlplane.tar.gz
      - name: {{ include "cluster-api.crdInstall" . }}-bootstrap
        configMap:
          name: {{ include "cluster-api.crdInstall" . }}-bootstrap
          items:
          - key: bootstrap.tar.gz
            path: bootstrap.tar.gz
      - name: {{ include "cluster-api.crdInstall" . }}-kustomization
        configMap:
          name: {{ include "cluster-api.crdInstall" . }}-kustomization
          items:
          - key: kustomization.yaml
            path: kustomization.yaml
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
