{{- if .Values.crds.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - patch
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions/status
  verbs:
  - get
  - patch
  - list
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "cluster-api.crdInstall" . }}
  verbs:
  - use
{{- end }}
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - patch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-api.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-api.crdInstall" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-api.crdInstall" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
