{{- if .Values.crds.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api.crdInstall" . }}-core
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
binaryData:
  core.tar.gz: |
{{ (.Files.Get "files/core.tar.gz" | b64enc | indent 4)}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api.crdInstall" . }}-controlplane
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
binaryData:
  controlplane.tar.gz: |
{{ (.Files.Get "files/controlplane.tar.gz" | b64enc | indent 4)}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api.crdInstall" . }}-bootstrap
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
binaryData:
  bootstrap.tar.gz: |
{{ (.Files.Get "files/bootstrap.tar.gz" | b64enc | indent 4)}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api.crdInstall" . }}-kustomization
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-5"
    {{- include "cluster-api.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "cluster-api.crdInstall" . | quote }}
    {{- include "cluster-api.selectorLabels" . | nindent 4 }}
    role: {{ include "cluster-api.CRDInstallSelector" . | quote }}
data:
  kustomization.yaml: |
{{ $.Files.Get "files/kustomization.yaml" | indent 4 }}
---
{{- end }}
