apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capi-serving-cert
  namespace: capi-system
spec:
  dnsNames:
  - capi-webhook-service.{{ .Release.Namespace }}.svc
  - capi-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: capi-webhook-service-cert
