# We deploy everything to giantswarm namespace.
---
$patch: delete
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
$patch: delete
apiVersion: v1
kind: Namespace
metadata:
  name: capi-webhook-system
---
$patch: delete
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-bootstrap-system
---
$patch: delete
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system
