# We are not deploying rbac-proxy (it has been removed in upstream as well).
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-proxy-role
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capi-proxy-rolebinding
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-kubeadm-bootstrap-proxy-role
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capi-kubeadm-bootstrap-proxy-rolebinding
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-kubeadm-control-plane-proxy-role
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capi-kubeadm-control-plane-proxy-rolebinding
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-controller-manager
  namespace: capi-webhook-system
spec:
  template:
    spec:
      containers:
      - $patch: delete
        name: kube-rbac-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-kubeadm-bootstrap-controller-manager
  namespace: capi-webhook-system
spec:
  template:
    spec:
      containers:
      - $patch: delete
        name: kube-rbac-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-kubeadm-control-plane-controller-manager
  namespace: capi-webhook-system
spec:
  template:
    spec:
      containers:
      - $patch: delete
        name: kube-rbac-proxy
