# We have our Issuer already deployed to clusters.
---
$patch: delete
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: capi-selfsigned-issuer
  namespace: capi-system
---
$patch: delete
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: capi-kubeadm-bootstrap-selfsigned-issuer
  namespace: capi-kubeadm-bootstrap-system
---
$patch: delete
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: capi-kubeadm-control-plane-selfsigned-issuer
  namespace: capi-kubeadm-control-plane-system
