apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-controller-manager
  namespace: capi-system
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --metrics-bind-addr=0.0.0.0:8080
            - --feature-gates=MachinePool=true,ClusterResourceSet=true,ClusterTopology=true
            - --watch-filter={{ .Values.watchFilter }}
            - --v=0
          image: '{{.Values.images.domain}}/{{.Values.images.core.name}}:{{.Values.images.core.tag | default .Values.images.tag}}'
