apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
    "helm.sh/hook-weight": "-1"
  name: helm-hook-delete-aggregated-roles
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-hook-delete-aggregated-roles
subjects:
  - kind: ServiceAccount
    name: helm-hook-delete-aggregated-roles
    namespace: '{{ .Release.Namespace }}'
