apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  name: helm-hook-delete-aggregated-roles
  namespace: '{{ .Release.Namespace }}'
