namespace: '{{ .Release.Namespace }}'

resources:
  - https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.0.2/cluster-api-components.yaml

images:
  - name: k8s.gcr.io/cluster-api/cluster-api-controller
    newName: "{{ .Values.registry.domain }}/{{ .Values.images.core.name }}"
    newTag: "{{ .Values.images.tag }}"
  - name: k8s.gcr.io/cluster-api/kubeadm-bootstrap-controller
    newName: "{{ .Values.registry.domain }}/{{ .Values.images.bootstrap.name }}"
    newTag: "{{ .Values.images.tag }}"
  - name: k8s.gcr.io/cluster-api/kubeadm-control-plane-controller
    newName: "{{ .Values.registry.domain }}/{{ .Values.images.controlplane.name }}"
    newTag: "{{ .Values.images.tag }}"

transformers:
  - common-labels.yaml
  - monitoring-annotations.yaml
  - webhook-prefix.yaml

patchesStrategicMerge:
  - deployment-args.yaml
  - deployment-metrics-port.yaml
  - delete-capi-system-ns.yaml
  - delete-capi-kubeadm-control-plane-system-ns.yaml
  - delete-capi-kubeadm-bootstrap-system-ns.yaml
  - webhook-watchfilter.yaml
  - webhook-certificate.yaml
  - service-add-metrics-port.yaml
  - certificate.yaml
