---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: capi-mutating-webhook-configuration
webhooks:
  - name: default.cluster.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: default.clusterclass.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: default.machine.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: default.machinedeployment.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: default.machinehealthcheck.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: default.machineset.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: default.machinepool.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: default.clusterresourceset.addons.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: capi-validating-webhook-configuration
webhooks:
  - name: validation.cluster.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: validation.clusterclass.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: validation.machine.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: validation.machinedeployment.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: validation.machinehealthcheck.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: validation.machineset.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: validation.machinepool.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: validation.clusterresourceset.addons.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: capi-kubeadm-control-plane-mutating-webhook-configuration
webhooks:
  - name: default.kubeadmcontrolplane.controlplane.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: default.kubeadmcontrolplanetemplate.controlplane.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: capi-kubeadm-control-plane-validating-webhook-configuration
webhooks:
  - name: validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
  - name: validation.kubeadmcontrolplanetemplate.controlplane.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: capi-kubeadm-bootstrap-validating-webhook-configuration
webhooks:
  - name: validation.kubeadmconfig.bootstrap.cluster.x-k8s.io
    objectSelector:
      matchLabels:
        cluster.x-k8s.io/watch-filter: capi
