apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-api.delete-aggregated-roles.fullname" . }}
  labels:
    {{- include "cluster-api.delete-aggregated-roles.labels" . | nindent 4 }}
  annotations:
    {{- include "cluster-api.delete-aggregated-roles.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-api.delete-aggregated-roles.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-api.delete-aggregated-roles.fullname" . }}
  namespace: {{ .Release.Namespace }}
