apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api.delete-aggregated-roles.fullname" . }}
  labels:
    {{- include "cluster-api.delete-aggregated-roles.labels" . | nindent 4 }}
  annotations:
    {{- include "cluster-api.delete-aggregated-roles.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-2"
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - delete
