apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cluster-api.delete-aggregated-roles.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api.delete-aggregated-roles.labels" . | nindent 4 }}
  annotations:
    {{- include "cluster-api.delete-aggregated-roles.annotations" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "cluster-api.delete-aggregated-roles.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cluster-api.delete-aggregated-roles.fullname" . }}
      automountServiceAccountToken: true
      containers:
      - name: kubectl
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        image: "{{ .Values.registry.domain }}/giantswarm/docker-kubectl:1.33.4"
        args:
        - delete
        - clusterrole
        - --ignore-not-found
        - capi-aggregated-manager-role
        - capi-kubeadm-control-plane-aggregated-manager-role
      restartPolicy: Never
