apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: delete-aggregated-roles
  namespace: '{{ .Release.Namespace }}'
  labels:
    helm.sh/chart: cluster-api
    app.kubernetes.io/name: cluster-api
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/component: delete-aggregated-roles
    application.giantswarm.io/branch: '{{ .Values.project.branch }}'
    application.giantswarm.io/commit: '{{ .Values.project.commit }}'
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cluster-api
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: delete-aggregated-roles
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 6443
      protocol: TCP
