apiVersion: v1
kind: Service
metadata:
  labels:
    application.giantswarm.io/branch: '{{ .Values.project.branch }}'
    application.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: cluster-api
    helm.sh/chart: cluster-api
  name: capi-webhook-service
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - name: webhook-server
    port: 443
    targetPort: webhook-server
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    cluster.x-k8s.io/provider: cluster-api
