version: 2.1
orbs:
  architect: giantswarm/architect@4.24.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation
          name: push-cluster-api-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-api"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/     
      - architect/push-to-app-collection:
          name: capa-app-collection
          context: "architect"
          app_name: "cluster-api"
          app_namespace: "giantswarm"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-cluster-api-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
