apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: capi-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/capi-serving-cert"
