apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: capi-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/capi-serving-cert'
