apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.core.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common.core" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.selector.core" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.common.core" . | nindent 8 }}
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-bind-addr=0.0.0.0:{{ .Values.ports.metrics }}
        - --feature-gates=MachinePool={{ .Values.featuregates.machinepool }},ClusterResourceSet={{ .Values.featuregates.clusterresourceset }}
        - --watch-filter={{ .Values.watchfilter }}
        - --webhook-port={{ .Values.ports.webhook }}
        command:
        - /manager
        image: "{{ .Values.registry.domain }}/{{ .Values.images.core.name }}:{{ .Values.images.tag }}"
        livenessProbe:
          tcpSocket:
            host: ""
            port: healthz
        name: manager
        ports:
        - containerPort: {{ .Values.ports.healthz }}
          name: healthz
          protocol: TCP
        - containerPort: {{ .Values.ports.metrics }}
          name: metrics
          protocol: TCP
        - containerPort: {{ .Values.ports.webhook }}
          name: webhook
          protocol: TCP
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
        readinessProbe:
          tcpSocket:
            host: ""
            port: healthz
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ include "resource.core.name"  . }}
      restartPolicy: Always
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ include "resource.core.name" . }}-cert
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
