apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/capi-serving-cert'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: cluster-api
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: cluster-api
    helm.sh/chart: cluster-api
  name: capi-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-cluster-x-k8s-io-v1alpha3-cluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.cluster.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-cluster-x-k8s-io-v1alpha3-machine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.machine.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - machines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-cluster-x-k8s-io-v1alpha3-machinedeployment
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.machinedeployment.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinedeployments
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-cluster-x-k8s-io-v1alpha3-machinehealthcheck
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.machinehealthcheck.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinehealthchecks
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-cluster-x-k8s-io-v1alpha3-machineset
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.machineset.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinesets
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-exp-cluster-x-k8s-io-v1alpha3-machinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.exp.machinepool.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - exp.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - machinepools
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: capi-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-addons-cluster-x-k8s-io-v1alpha3-clusterresourceset
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.clusterresourceset.addons.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - addons.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterresourcesets
  sideEffects: None
