apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: capi-kubeadm-control-plane-controller-manager
  namespace: capi-kubeadm-control-plane-system
  labels:
    app.kubernetes.io/component: control-plane-kubeadm
    cluster.x-k8s.io/provider: control-plane-kubeadm
    control-plane: controller-manager
spec:
  endpointSelector:
    matchLabels:
      cluster.x-k8s.io/provider: control-plane-kubeadm
      control-plane: controller-manager
  ingress:
  - fromEntities:
    - cluster
    - kube-apiserver
  egress:
  - toEntities:
    - kube-apiserver
