- op: replace
  path: /spec/versions/1/schema
  value:
    openAPIV3Schema:
      description: IPAddressClaim is the Schema for the ipaddressclaim API.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: IPAddressClaimSpec is the desired state of an IPAddressClaim.
          properties:
            clusterName:
              description: clusterName is the name of the Cluster this object belongs to.
              type: string
            poolRef:
              description: poolRef is a reference to the pool from which an IP address should be created.
              properties:
                apiGroup:
                  description: |-
                    APIGroup is the group for the resource being referenced.
                    If APIGroup is not specified, the specified Kind must be in the core API group.
                    For any other third-party types, APIGroup is required.
                  type: string
                kind:
                  description: Kind is the type of resource being referenced
                  type: string
                name:
                  description: Name is the name of resource being referenced
                  type: string
              required:
                - kind
                - name
              type: object
              x-kubernetes-map-type: atomic
          required:
            - poolRef
          type: object
        status:
          description: IPAddressClaimStatus is the observed status of a IPAddressClaim.
          properties:
            addressRef:
              description: addressRef is a reference to the address that was created for this claim.
              properties:
                name:
                  default: ""
                  description: |-
                    Name of the referent.
                    This field is effectively required, but due to backwards compatibility is
                    allowed to be empty. Instances of this type with an empty value here are
                    almost certainly wrong.
                    More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                  type: string
              type: object
              x-kubernetes-map-type: atomic
            conditions:
              description: conditions summarises the current state of the IPAddressClaim
              items:
                description: Condition defines an observation of a Cluster API resource operational state.
                properties:
                  lastTransitionTime:
                    description: |-
                      Last time the condition transitioned from one status to another.
                      This should be when the underlying condition changed. If that is not known, then using the time when
                      the API field changed is acceptable.
                    format: date-time
                    type: string
                  message:
                    description: |-
                      A human readable message indicating details about the transition.
                      This field may be empty.
                    type: string
                  reason:
                    description: |-
                      The reason for the condition's last transition in CamelCase.
                      The specific API may choose whether or not this field is considered a guaranteed API.
                      This field may be empty.
                    type: string
                  severity:
                    description: |-
                      severity provides an explicit classification of Reason code, so the users or machines can immediately
                      understand the current situation and act accordingly.
                      The Severity field MUST be set only when Status=False.
                    type: string
                  status:
                    description: status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: |-
                      type of condition in CamelCase or in foo.example.com/CamelCase.
                      Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
                      can be useful (see .node.status.conditions), the ability to deconflict is important.
                    type: string
                required:
                  - lastTransitionTime
                  - status
                  - type
                type: object
              type: array
          type: object
      type: object
