apiVersion: apps/v1
kind: Deployment
metadata:
  name: all
spec:
  template:
    spec:
      containers:
      - name: manager
        ports:
        - $patch: delete
          name: metrics
          protocol: TCP
          containerPort: 8443
