apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-kubeadm-control-plane-controller-manager
  namespace: capi-kubeadm-control-plane-system
  labels:
    app.kubernetes.io/component: control-plane-kubeadm
spec:
  template:
    spec:
      securityContext:
        seccompProfile:
          $patch: delete
      containers:
      - name: manager
        args:
        - --metrics-bind-addr=0.0.0.0:8080
        - --feature-gates=ClusterTopology=true,KubeadmBootstrapFormatIgnition=true
        - --watch-filter={{ .Values.watchFilter }}
        - --v=0
        ports:
        - name: metrics
          protocol: TCP
          containerPort: 8080
