apiVersion: v1
kind: Service
metadata:
  name: capi-kubeadm-control-plane-webhook-service
  namespace: capi-kubeadm-control-plane-system
spec:
  ports:
  - name: webhook-server
    port: 443
    targetPort: webhook-server
  - name: metrics
    port: 8080
    targetPort: metrics
