checks:
  exclude:
    # Upstream CAPI templates - cannot modify
    - no-read-only-root-fs
    - unset-cpu-requirements
    - unset-memory-requirements
    # CRD install and cleanup jobs
    - job-ttl-seconds-after-finished

