resources:
  - bases/kubeadmcontrolplanes.controlplane.cluster.x-k8s.io.yaml
patches:
  - path: patches/versions/v1alpha3/kubeadmcontrolplanes.controlplane.cluster.x-k8s.io.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: kubeadmcontrolplanes.controlplane.cluster.x-k8s.io
