apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capi-kubeadm-control-plane-serving-cert
  namespace: capi-kubeadm-control-plane-system
spec:
  dnsNames:
  - capi-kubeadm-control-plane-webhook-service.{{ .Release.Namespace }}.svc
  - capi-kubeadm-control-plane-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
