name: Templates
on: pull_request
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: verify
        run: make verify
